### ISSUE TITLE
Support for Scala 2.11

### ISSUE THREAD

**Issue by eximius313** [matthewrennie/sbt-autoprefixer#6]
Do you plan to support scala 2.11?

Kind regards

**Comment by mkurz** [comment]
Hi @eximius313,

as @matthewrennie wrote [here](https://github.com/matthewrennie/sbt-autoprefixer/issues/4#issuecomment-63980174) he does not plan to maintain the project anymore.

Check out my fork: https://github.com/mkurz/sbt-autoprefixer
I have done some updates and it works fine with Play 2.4.

**Comment by eximius313** [comment]
indeed your version is working just fine, thanks!
